apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: kubernetes.io/basic-auth
stringData:
  username: 'gaber' # create use called appuser 
  password: '123' # create password its value is 123