apiVersion: v1
kind: Secret

metadata:
  name: alertmanager-main-secret
  namespace: prometheus-ns

stringData: # config map
  alertmanager.yaml: |
    global:
      resolve_timeout: 1m

      smtp_smarthost: smtp.gmail.com:587
      smtp_from: "youssef11gaber10@gmail.com"
      smtp_auth_username: "youssef11gaber10@gmail.com"
      smtp_auth_password: "app_password"

    receivers:

      - name: default_email

        email_configs:
          - to: yooossef11gaber10@gmail.com
            send_resolved: true

      - name: warn_email

        email_configs:
          - to: yoossef11gaber10@gmail.com
            send_resolved: true

      - name: slack_for_critical_alerts

        slack_configs:
          - api_url: "webhook_url"
            channel: '#promethues_channel'
            send_resolved: true

    route:
      receiver: default_email

      group_by: ['...']

      group_wait: 1s
      group_interval: 1s
      repeat_interval: 1m

      routes:

        - matchers:
            - severity="warning"

          receiver: warn_email

          group_by:
            - alertname

          group_wait: 10s
          group_interval: 10s
          repeat_interval: 1m

        - matchers:
            - severity="critical"

          receiver: slack_for_critical_alerts

          group_by:
            - instance

          group_wait: 30s
          group_interval: 30s
          repeat_interval: 30s