apiVersion: monitoring.coreos.com/v1
kind: Alertmanager

metadata:
  name: main-alertmanager
  namespace: prometheus-ns

spec:
  replicas: 1

  configSecret: alertmanager-main-secret

  resources:
    requests:
      memory: 64Mi
      cpu: 250m

    limits:
      memory: 128Mi
      cpu: 500m
