apiVersion: v1
kind: Secret
metadata:
  name: mariadb
type: Opaque
# data: # this if i store data as base64 encoded string
#   password: <Password>
# but i will make it as string data and leave k8s to encode it
stringData:
  password: '123'
