apiVersion: v1
kind: Service
metadata:
  name: prometheus-headless-svc
  namespace: prometheus-ns
spec:
  clusterIP: None 
  selector:
    app: prometheus-pod
  ports:
  - port: 9090
    targetPort: 9090
